apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/argo-cd/
    repoURL: https://github.com/argoproj/argo-helm.git
    targetRevision: HEAD
    helm:
      values: |
        dex:
          enabled: false
        notifications:
          enabled: false
        applicationSet:
          enabled: false
        server:
          extraArgs:
            - --insecure
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true

