apiVersion: ec2.aws.upbound.io/v1beta1
kind: Instance
metadata:
  name: webapp-ec2
  labels:
    environment: production
    app: webapp
    owner: webdevs1
spec:
  forProvider:
    region: us-east-1
    ami: ami-0230bd60aa48260c6
    instanceType: t2.micro
    keyName: crossplane_key
  providerConfigRef:
    name: default
