apiVersion: ec2.aws.upbound.io/v1beta1
kind: InternetGateway
metadata:
  name: webapp-routegw
  labels:
    environment: production
    app: webapp
    owner: webdevs1
spec:
  forProvider:
    region: us-east-1
    tags:
      Name: main
    vpcIdRef:
      name: production-vpc
  providerConfigRef:
    name: default

