apiVersion: ec2.aws.upbound.io/v1beta1
kind: MainRouteTableAssociation
metadata:
  labels:
    environment: production
    app: webapp
    owner: webdevs1
  name: webapp-public
spec:
  forProvider:
    region: us-east-1
    routeTableIdRef:
      name: prod-public-route
    vpcIdRef:
      name: production-vpc 
  providerConfigRef:
    name: default
