apiVersion: ec2.aws.upbound.io/v1beta1
kind: NATGateway
metadata:
  name: webapp-natgw
  labels:
    environment: production
    app: webapp
    owner: webdevs1
spec:
  forProvider:
    connectivityType: public
    allocationId: eip1
    region: us-east-1
    subnetIdRef:
      name: subnet-east-1b
    tags:
      Name: gw NAT
  providerConfigRef:
    name: default

