apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTableAssociation 
metadata:
  labels:
    environment: production
    app: webapp
    owner: webdevs1
  name: webapp-public
spec:
  forProvider:
    region: us-east-1
    subnetIdRef:
      name: subnet-east-1b
    routeTableIdRef:
      name: prod-public-route
