---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTable
metadata:
  labels:
    environment: production
    app: webapp
    owner: webdevs1
  name: public-route-table
spec:
  forProvider:
    region: us-east-1
    vpcIdRef:
      name: production-vpc
  providerConfigRef:
    name: default
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTable
metadata:
  labels:
    environment: production
    app: webapp
    owner: webdevs1
  name: private-route-table
spec:
  forProvider:
    region: us-east-1
    vpcIdRef:
      name: production-vpc
  providerConfigRef:
    name: default


