---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupRule
metadata:
  labels:
    environment: production
    app: webapp
    owner: webdevs1
  name: webapp-allow-ssh
spec:
  forProvider:
    region: us-east-1
    cidrBlocks: 
      - 0.0.0.0/0
    fromPort: 22
    toPort: 22
    protocol: tcp
    type: ingress
  providerConfigRef:
    name: default
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupRule
metadata:
  labels:
    environment: production
    app: webapp
    owner: webdevs1
  name: allow-egress
spec:
  forProvider:
    region: us-east-1
    cidrBlocks: 
      - 0.0.0.0/0
    fromPort: 0
    toPort: 0
    protocol: all
    type: egress
  providerConfigRef:
    name: default

