apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: charts/argo-cd
    repoURL: 'https://github.com/capgainschristian/crossplane-aws-ready'
    targetRevision: HEAD
  project: argocd
  syncPolicy:
    automated:
      selfHeal: true

