apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: in-cluster
  project: aws
  source:
    path: crossplane/aws/resources/
    repoURL: https://github.com/capgainschristian/crossplane-aws-ready
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
