apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: default
  source:
    path: charts/apps/
    repoURL: 'https://github.com/capgainschristian/crossplane-aws-ready'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      selfHeal: true

